title: Lucius Party 2018
description: > # this means to ignore newlines until "baseurl:"
  Your description
baseurl: "" # the subpath of your site, e.g. /blog
url: "luciusparty.com " # the base hostname & protocol for your site
# Build settings
markdown: kramdown

include: ['_2016_pages', '_2017_pages']

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)


# Build settings
markdown: kramdown
permalink: pretty